### ISSUE TITLE
Config::isSet and C::DEFAULT causing errors on PHP 5.6

### ISSUE THREAD

**Issue by joshbmarshall** [ncjoes/pdf-suite#1]
As isset and default are reserved keywords, it's causing an error message on PHP 5.6

Renaming slightly fixes the problem

**Comment by pankajmanay** [comment]
What needs to be renamed? Can you please suggest

**Comment by joshbmarshall** [comment]
The words "isset" and "default" need to be renamed. Even if changed to is_set and default_something would likely work.

**Comment by pankajmanay** [comment]
Thanks for the reply, When i change it to is_set, it is giving me the following error

ErrorException in /var/www/html/proj10/vendor/ncjoes/poppler-php/src/PopplerPhp/Config.php line 30: call_user_func_array() expects parameter 1 to be a valid callback, class 'Illuminate\Config\Repository' does not have a method 'is_Set'

**Comment by joshbmarshall** [comment]
sounds like you did a global search and replace, and it's changed a real isset to is_set. maybe instead search for ::isset ?
Sorry I don't use this project, found something else that worked for me. Was just reporting it in case you wanted to support PHP5.6 - you do have the option to change the composer description to require >5.6
